### ISSUE TITLE
assert errors  e.g. assert_test_col in grouped_predict_inla_ts

### ISSUE THREAD

**Issue by alicerobson** [caldwellst/augury#1]
Thought I would try this out :-). Example that generates issue is attached.

Also applies to predict_inla

Error in assert_test_col(df[[test_col]]) : 
  argument "test_col" is missing, with no default

I think there are more of these issues 
Error in assert_df(df) : could not find function "assert_df"

and what do I do if tying to fix a bug and get to code that is not exported. Maybe would be good to export everything during initial phases?

 augury::get_model_data

Error: 'get_model_data' is not an exported object from 'namespace:augury'

[error_augury.txt](https://github.com/caldwellst/augury/files/5859958/error_augury.txt)

**Comment by caldwellst** [comment]
Okay great, I just fixed this error when addressing the other issue. If you want to try and assess a bug in functions that aren't exported, you can just use `augury:::` to access any non-exported functions. Or if you clone this development repository while testing, the RStudio development tools allow you to load all function objects into your environment, regardless of if they are exported or not (a huge advantage of the RStudio IDE when developing packages is the additional functionality like this). 

I won't export all objects yet because I think the options above are cleaner/the better proces, but let me know how you get on.
